async function servicesCommand(sock, chatId, message) {
    try {
        const servicesMessage = `
╭━━━━━━━━━━━━━━━━━━╮
│  💼 *OUR SERVICES* 💼  │
╰━━━━━━━━━━━━━━━━━━╯

*1. 📧 BUSINESS EMAIL SERVICES*
   • Custom Domain Email (@infontandostore@no.vsmailpro.com)
   • Unlimited Email Accounts
   • 99.9% Uptime Guarantee
   • Spam Protection
   • Mobile & Desktop Access
   💰 Starting from $11.99/month

*2. 🌐 DOMAIN SERVICES*
   • .com, .net, .org domains
   • Free WHOIS Privacy
   • Easy DNS Management
   • Domain Transfer Support
   💰 Starting from $19.99/year

*3. 🤖 WHATSAPP BOT DEVELOPMENT*
   • Custom Features
   • Group Management
   • Auto-Reply System
   • Admin Tools
   • 24/7 Operation
   💰 Starting from $10.99

*4. 🎨 DESIGN SERVICES*
   • Professional Logo Design
   • Business Card Design
   • Letterhead & Branding
   • Unlimited Revisions
   • Source Files Included
   💰 Starting from $29.99

*5. 🌍 WEBSITE SERVICES*
   • Responsive Website Design
   • E-commerce Development
   • SEO Optimization
   • Fast Hosting
   • SSL Certificate Included
   💰 Starting from $35.99

*6. 🖥️ WEBSITE HOSTING*
   • 99.9% Uptime
   • Free SSL Certificate
   • Daily Backups
   • 24/7 Support
   • cPanel Access
   💰 Starting from $4.99/month

*📧 Get a Quote:*
Email: infontandostore@no.vsmailpro.com

*🛒 Order Now:*
Type *.store* to see all services

_Generated by Ladybug_`;

        await sock.sendMessage(chatId, { 
            text: servicesMessage 
        }, { quoted: message });

    } catch (error) {
        console.error('Error in services command:', error);
        await sock.sendMessage(chatId, { 
            text: '❌ Failed to load services information.' 
        }, { quoted: message });
    }
}

module.exports = servicesCommand;
