async function storeCommand(sock, chatId, message) {
    try {
        const storeMessage = `
╭━━━━━━━━━━━━━━━━━━╮
│  🛒 *INFONTANDO STORE* 🛒  │
╰━━━━━━━━━━━━━━━━━━╯

Welcome to Infontando Store! We offer professional digital services:

*📧 Email Services*
• Business Emails with Custom Domain
• Professional Email Solutions
• Secure Email Hosting

*🌐 Domain Services*
• Domain Registration
• Domain Transfer
• Custom Domain Setup

*🤖 WhatsApp Bot Development*
• Custom WhatsApp Bots
• Feature-Rich Automation
• Group Management Bots

*💼 Design Services*
• Professional Business Logos
• Business Card Design
• Brand Identity Design

*🌍 Website Services*
• Website Design & Development
• Website Hosting
• E-commerce Solutions
• Responsive Web Design

*📞 Contact Us:*
📧 Email: infontandostore@no.vsmailpro.com

*💡 Need Help?*
Type *.support* for assistance

╭━━━━━━━━━━━━━━━━━━╮
│ *Quality Service Guaranteed* │
╰━━━━━━━━━━━━━━━━━━╯

_Generated by Ladybug_`;

        await sock.sendMessage(chatId, { 
            text: storeMessage 
        }, { quoted: message });

    } catch (error) {
        console.error('Error in store command:', error);
        await sock.sendMessage(chatId, { 
            text: '❌ Failed to load store information.' 
        }, { quoted: message });
    }
}

module.exports = storeCommand;
