async function supportCommand(sock, chatId, message) {
    try {
        const supportMessage = `
╭━━━━━━━━━━━━━━━━━━╮
│  🆘 *SUPPORT CENTER* 🆘  │
╰━━━━━━━━━━━━━━━━━━╯

Need help? We're here for you!

*📞 How to Get Support:*

1️⃣ *Email Support*
   📧 infontandostore@no.vsmailpro.com
   ⏰ Response time: 24-48 hours

2️⃣ *WhatsApp Support*
   📱 263718456744 

3️⃣ *Bot Commands Help*
   Type *.help* to see all available commands

*🛍️ Services We Support:*
✅ Business Email Setup
✅ Domain Configuration
✅ WhatsApp Bot Installation
✅ Website Hosting Issues
✅ Logo & Design Revisions
✅ Technical Assistance

*💼 Business Inquiries:*
For new orders or custom projects:
📧 infontandostore@no.vsmailpro.com

*⚡ Quick Links:*
• Store: *.store*
• Commands: *.help*
• Bot Info: *.alive*

╭━━━━━━━━━━━━━━━━━━╮
│ *We're Here to Help 24/7* │
╰━━━━━━━━━━━━━━━━━━╯

_Generated by Ladybug_`;

        await sock.sendMessage(chatId, { 
            text: supportMessage 
        }, { quoted: message });

    } catch (error) {
        console.error('Error in support command:', error);
        await sock.sendMessage(chatId, { 
            text: '❌ Failed to load support information.' 
        }, { quoted: message });
    }
}

module.exports = supportCommand;
